"""Configured values for Wayland's Bazel overlay."""

_SOVERSION = "0"
CURSOR_ICONDIR = "/usr/share/icons"

SHARED_LIB_NAME = {
    "client": "libwayland-client.so.%s" % _SOVERSION,
    "cursor": "libwayland-cursor.so.%s" % _SOVERSION,
    "egl": "libwayland-egl.so.1",
    "server": "libwayland-server.so.%s" % _SOVERSION,
}

SHARED_LIB_LINKOPTS = {
    "client": ["-Wl,-soname,%s" % SHARED_LIB_NAME["client"]],
    "cursor": ["-Wl,-soname,%s" % SHARED_LIB_NAME["cursor"]],
    "egl": ["-Wl,-soname,%s" % SHARED_LIB_NAME["egl"]],
    "server": ["-Wl,-soname,%s" % SHARED_LIB_NAME["server"]],
}

COMMON_COPTS = [
    "-std=c99",
    "-fexceptions",
    "-D_POSIX_C_SOURCE=200809L",
    "-Wno-unused-parameter",
    "-Wstrict-prototypes",
    "-Wmissing-prototypes",
    "-fvisibility=hidden",
]

LINUX_SRCS = {
    "@platforms//os:linux": [],
    "//conditions:default": ["@platforms//:incompatible"],
}

def _components(version):
    components = []
    for part in (version or "0.0.0").split(".")[:3]:
        digits = ""
        for char in part.elems():
            if not char.isdigit():
                break
            digits += char
        components.append(int(digits) if digits else 0)
    return components

def wayland_version_substitutions(version):
    major, minor, micro = _components(version)
    return {
        "@WAYLAND_VERSION@": "%d.%d.%d" % (major, minor, micro),
        "@WAYLAND_VERSION_MAJOR@": str(major),
        "@WAYLAND_VERSION_MINOR@": str(minor),
        "@WAYLAND_VERSION_MICRO@": str(micro),
    }

def _config_h(version):
    return """\
/*
 * Autogenerated by the Bazel build.
 * Do not edit, your changes will be lost.
 */

#pragma once

#undef HAVE_ACCEPT4

#define HAVE_BROKEN_MSG_CMSG_CLOEXEC 0

#undef HAVE_GETTID

#undef HAVE_MEMFD_CREATE

#undef HAVE_MKOSTEMP

#undef HAVE_MREMAP

#undef HAVE_POSIX_FALLOCATE

#undef HAVE_PRCTL

#undef HAVE_STRNDUP

#undef HAVE_SYS_PRCTL_H

#undef HAVE_SYS_PROCCTL_H

#undef HAVE_SYS_UCRED_H

#define HAVE_XUCRED_CR_PID 0

#define PACKAGE "wayland"

#define PACKAGE_VERSION "%s"
""" % version

def _generate_config_h_impl(ctx):
    ctx.actions.write(
        output = ctx.outputs.out,
        content = _config_h(ctx.attr.version),
    )
    return DefaultInfo(files = depset([ctx.outputs.out]))

generate_config_h = rule(
    implementation = _generate_config_h_impl,
    attrs = {
        "out": attr.output(mandatory = True),
        "version": attr.string(mandatory = True),
    },
)
